/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Computer_Category;

import QandA.front;
import javax.swing.JOptionPane;

/**
 *
 * @author micojasmin
 */

class hp2 extends hp1{
    
}
public class Cat3 extends javax.swing.JFrame {
        
    hp2 h2 = new hp2();
    public Cat3() {
        initComponents();
        jButtonCheck.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButtonEncapsulation = new javax.swing.JRadioButton();
        jRadioButtonPOLY = new javax.swing.JRadioButton();
        jRadioButtonAbstract = new javax.swing.JRadioButton();
        jRadioButtonInterface = new javax.swing.JRadioButton();
        jButtonCheck = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Which one is not part of 4 instance of \nObject Oriented Programming (OOP)?");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 420, 80);

        jRadioButtonEncapsulation.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButtonEncapsulation.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonEncapsulation.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonEncapsulation.setText("Encapsulation");
        jRadioButtonEncapsulation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonEncapsulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEncapsulationActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonEncapsulation);
        jRadioButtonEncapsulation.setBounds(240, 200, 200, 40);

        jRadioButtonPOLY.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButtonPOLY.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonPOLY.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonPOLY.setText("Polymorphism");
        jRadioButtonPOLY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonPOLY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPOLYActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonPOLY);
        jRadioButtonPOLY.setBounds(20, 200, 200, 40);

        jRadioButtonAbstract.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButtonAbstract.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonAbstract.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonAbstract.setText("Abstract Class");
        jRadioButtonAbstract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonAbstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAbstractActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonAbstract);
        jRadioButtonAbstract.setBounds(20, 140, 200, 40);

        jRadioButtonInterface.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButtonInterface.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonInterface.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonInterface.setText("Interface");
        jRadioButtonInterface.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonInterfaceActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonInterface);
        jRadioButtonInterface.setBounds(240, 140, 200, 40);

        jButtonCheck.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jButtonCheck.setText("Check");
        jButtonCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCheck);
        jButtonCheck.setBounds(350, 250, 90, 35);

        jButton2.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 250, 90, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAbstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAbstractActionPerformed
  if (jRadioButtonAbstract.isSelected()) {
            jButtonCheck.setVisible(true);
            jRadioButtonEncapsulation.setEnabled(false);
            jRadioButtonInterface.setEnabled(false);
            jRadioButtonPOLY.setEnabled(false);

        } else if (!jRadioButtonAbstract.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonEncapsulation.setEnabled(true);
            jRadioButtonInterface.setEnabled(true);
            jRadioButtonPOLY.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonAbstractActionPerformed

    private void jRadioButtonInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonInterfaceActionPerformed
         if (jRadioButtonInterface.isSelected()) {
             jButtonCheck.setVisible(true);
            jRadioButtonEncapsulation.setEnabled(false);
            jRadioButtonAbstract.setEnabled(false);
            jRadioButtonPOLY.setEnabled(false);

        } else if (!jRadioButtonInterface.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonEncapsulation.setEnabled(true);
            jRadioButtonAbstract.setEnabled(true);
            jRadioButtonPOLY.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonInterfaceActionPerformed

    private void jRadioButtonPOLYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPOLYActionPerformed
         if (jRadioButtonPOLY.isSelected()) {
             jButtonCheck.setVisible(true);
            jRadioButtonEncapsulation.setEnabled(false);
            jRadioButtonInterface.setEnabled(false);
            jRadioButtonAbstract.setEnabled(false);

        } else if (!jRadioButtonPOLY.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonEncapsulation.setEnabled(true);
            jRadioButtonInterface.setEnabled(true);
            jRadioButtonAbstract.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonPOLYActionPerformed

    private void jRadioButtonEncapsulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEncapsulationActionPerformed
         if (jRadioButtonEncapsulation.isSelected()) {
             jButtonCheck.setVisible(true);
            jRadioButtonAbstract.setEnabled(false);
            jRadioButtonInterface.setEnabled(false);
            jRadioButtonPOLY.setEnabled(false);

        } else if (!jRadioButtonEncapsulation.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonAbstract.setEnabled(true);
            jRadioButtonInterface.setEnabled(true);
            jRadioButtonPOLY.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonEncapsulationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Cat2().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckActionPerformed
               
        if (jRadioButtonInterface.isSelected()) {

            JOptionPane.showMessageDialog(rootPane, "YOUR ANSWER IS CORRECT");
            new Cat4().setVisible(true);
            setVisible(false);
        } else if (!jRadioButtonInterface.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "YOUR ANSWER IS WRONG" + "\n" + --h2.life +" "+ "LIVES LEFT");
            if (h2.life == 0) {
                h2.life=3;
                JOptionPane.showMessageDialog(rootPane, "GAME OVER!");
                new front().setVisible(true);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_jButtonCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cat3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAbstract;
    private javax.swing.JRadioButton jRadioButtonEncapsulation;
    private javax.swing.JRadioButton jRadioButtonInterface;
    private javax.swing.JRadioButton jRadioButtonPOLY;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
