/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Computer_Category;

import QandA.front;
import javax.swing.JOptionPane;

/**
 *
 * @author micojasmin
 */
class hp4 extends hp3{
    
}
public class Cat5 extends javax.swing.JFrame {
hp4 h4 = new hp4();
    /**
     * Creates new form Cat5
     */
    public Cat5() {
        initComponents();
        jButtonCheck.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButtonDataProcessing = new javax.swing.JRadioButton();
        jRadioButtonTransmission = new javax.swing.JRadioButton();
        jRadioButtonDataFlow = new javax.swing.JRadioButton();
        jRadioButtonDataCapture = new javax.swing.JRadioButton();
        jButtonCheck = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("A computer assisted method for the \nrecording and analyzing of existing or \nhypothetical systems is?\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(24, 21, 415, 110);

        jRadioButtonDataProcessing.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonDataProcessing.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonDataProcessing.setText("Data Processing");
        jRadioButtonDataProcessing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonDataProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDataProcessingActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonDataProcessing);
        jRadioButtonDataProcessing.setBounds(240, 210, 200, 40);

        jRadioButtonTransmission.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonTransmission.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonTransmission.setText("Data Transmission");
        jRadioButtonTransmission.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonTransmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTransmissionActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonTransmission);
        jRadioButtonTransmission.setBounds(21, 149, 200, 40);

        jRadioButtonDataFlow.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonDataFlow.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonDataFlow.setText("Data Flow");
        jRadioButtonDataFlow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonDataFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDataFlowActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonDataFlow);
        jRadioButtonDataFlow.setBounds(240, 150, 200, 40);

        jRadioButtonDataCapture.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jRadioButtonDataCapture.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonDataCapture.setText("Data Capture");
        jRadioButtonDataCapture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonDataCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDataCaptureActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonDataCapture);
        jRadioButtonDataCapture.setBounds(20, 210, 200, 40);

        jButtonCheck.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jButtonCheck.setText("Check");
        jButtonCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCheck);
        jButtonCheck.setBounds(350, 270, 90, 35);

        jButton2.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 270, 91, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTransmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTransmissionActionPerformed
         if (jRadioButtonTransmission.isSelected()) {
             jButtonCheck.setVisible(true);
            jRadioButtonDataCapture.setEnabled(false);
            jRadioButtonDataFlow.setEnabled(false);
            jRadioButtonDataProcessing.setEnabled(false);

        } else if (!jRadioButtonTransmission.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonDataCapture.setEnabled(true);
            jRadioButtonDataFlow.setEnabled(true);
            jRadioButtonDataProcessing.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonTransmissionActionPerformed

    private void jRadioButtonDataFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDataFlowActionPerformed
         if (jRadioButtonDataFlow.isSelected()) {
             jButtonCheck.setVisible(true);
            jRadioButtonDataCapture.setEnabled(false);
            jRadioButtonTransmission.setEnabled(false);
            jRadioButtonDataProcessing.setEnabled(false);

        } else if (!jRadioButtonDataFlow.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonDataCapture.setEnabled(true);
            jRadioButtonTransmission.setEnabled(true);
            jRadioButtonDataProcessing.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonDataFlowActionPerformed

    private void jRadioButtonDataCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDataCaptureActionPerformed
         if (jRadioButtonDataCapture.isSelected()) {
             jButtonCheck.setVisible(true);
            jRadioButtonTransmission.setEnabled(false);
            jRadioButtonDataFlow.setEnabled(false);
            jRadioButtonDataProcessing.setEnabled(false);

        } else if (!jRadioButtonDataCapture.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonTransmission.setEnabled(true);
            jRadioButtonDataFlow.setEnabled(true);
            jRadioButtonDataProcessing.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonDataCaptureActionPerformed

    private void jRadioButtonDataProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDataProcessingActionPerformed
         if (jRadioButtonDataProcessing.isSelected()) {
             jButtonCheck.setVisible(true);
            jRadioButtonDataCapture.setEnabled(false);
            jRadioButtonDataFlow.setEnabled(false);
            jRadioButtonTransmission.setEnabled(false);

        } else if (!jRadioButtonDataProcessing.isSelected()) {
            jButtonCheck.setVisible(false);
            jRadioButtonDataCapture.setEnabled(true);
            jRadioButtonDataFlow.setEnabled(true);
            jRadioButtonTransmission.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonDataProcessingActionPerformed

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckActionPerformed
      if (jRadioButtonDataCapture.isSelected()) {

            JOptionPane.showMessageDialog(rootPane, "YOUR ANSWER IS CORRECT");
            new Cat6().setVisible(true);
            setVisible(false);
        } else if (!jRadioButtonDataCapture.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "YOUR ANSWER IS WRONG" + "\n" + --h4.life +" "+ "LIVES LEFT");
            if (h4.life == 0) {
                h4.life=3;
                JOptionPane.showMessageDialog(rootPane, "GAME OVER!");
                new front().setVisible(true);
                setVisible(false);
            }
        }        
    }//GEN-LAST:event_jButtonCheckActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Cat4().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cat5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cat5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButtonDataCapture;
    private javax.swing.JRadioButton jRadioButtonDataFlow;
    private javax.swing.JRadioButton jRadioButtonDataProcessing;
    private javax.swing.JRadioButton jRadioButtonTransmission;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
