/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QandA;

import Animals_Category.Animals01;
import Computer_Category.Cat1;
import Gaming_Category.Gaming1;
import java.awt.Color;


/**
 *
 * @author micojasmin
 */
class mylife  {
 static int life= 3;
}
public class Categories extends javax.swing.JFrame {

    /**
     * Creates new form Categories
     */
    public Categories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButtonComputers = new javax.swing.JButton();
        jButton1Sports = new javax.swing.JButton();
        jButtonGaming = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Noto Sans Mono", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText(" SELECT CATEGORY");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(70, 40, 240, 40);

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Back");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setIconTextGap(0);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 310, 90, 30);

        jButtonComputers.setBackground(new java.awt.Color(255, 255, 51));
        jButtonComputers.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonComputers.setForeground(new java.awt.Color(0, 0, 0));
        jButtonComputers.setText("COMPUTERS");
        jButtonComputers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonComputers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonComputers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonComputersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonComputersMouseExited(evt);
            }
        });
        jButtonComputers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputersActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonComputers);
        jButtonComputers.setBounds(20, 100, 150, 69);

        jButton1Sports.setBackground(new java.awt.Color(51, 51, 255));
        jButton1Sports.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton1Sports.setForeground(new java.awt.Color(204, 204, 204));
        jButton1Sports.setText("ANIMALS");
        jButton1Sports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1Sports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Sports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1SportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1SportsMouseExited(evt);
            }
        });
        jButton1Sports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SportsActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Sports);
        jButton1Sports.setBounds(190, 100, 150, 70);

        jButtonGaming.setBackground(new java.awt.Color(255, 51, 51));
        jButtonGaming.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonGaming.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGaming.setText("GAMING");
        jButtonGaming.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGaming.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGaming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGamingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonGamingMouseExited(evt);
            }
        });
        jButtonGaming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGamingActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGaming);
        jButtonGaming.setBounds(100, 180, 150, 66);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Front backgrounds/06bddf6da55366632f3f959fa214bd56.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-180, 0, 540, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGamingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGamingActionPerformed
        new Gaming1().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonGamingActionPerformed

    private void jButtonGamingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGamingMouseExited
        jButtonGaming.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_jButtonGamingMouseExited

    private void jButtonGamingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGamingMouseEntered
        jButtonGaming.setBackground(new Color(102,102,102));
        jButtonGaming.setForeground(Color.black);
    }//GEN-LAST:event_jButtonGamingMouseEntered

    private void jButton1SportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SportsActionPerformed
        new Animals01().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1SportsActionPerformed

    private void jButton1SportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1SportsMouseExited
        jButton1Sports.setBackground(new Color(51,51,255));
        jButton1Sports.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jButton1SportsMouseExited

    private void jButton1SportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1SportsMouseEntered
        jButton1Sports.setBackground(new Color(102,102,102));
        jButton1Sports.setForeground(Color.black);
    }//GEN-LAST:event_jButton1SportsMouseEntered

    private void jButtonComputersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputersActionPerformed

        new Cat1().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonComputersActionPerformed

    private void jButtonComputersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonComputersMouseExited
        jButtonComputers.setBackground(new Color(255,255,51));
    }//GEN-LAST:event_jButtonComputersMouseExited

    private void jButtonComputersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonComputersMouseEntered
        jButtonComputers.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_jButtonComputersMouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new front().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Sports;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonComputers;
    private javax.swing.JButton jButtonGaming;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
